const menu=document.querySelector('.menu');
const nav=document.querySelector('.topbar nav');
const topbar=document.querySelector('.topbar');
const hero=document.querySelector('.hero');

const translations={
  'Trayectoria':'Profile','Proyectos':'Projects','Soluciones':'Solutions','Tecnologías':'Technology','Ver tienda':'View catalog',
  'Pacífico Central · Costa Rica':'Central Pacific · Costa Rica','La tecnología se nota':'Technology stands out','cuando funciona.':'when it works.',
  'Diseñamos e instalamos seguridad, conectividad e infraestructura que se integra al espacio y responde cuando más se necesita.':'We design and install security, connectivity and infrastructure that blends into each space and responds when it matters most.',
  'Conversemos por WhatsApp':'Let’s talk on WhatsApp','Explorar proyectos':'Explore projects','Seguridad electrónica':'Electronic security','Redes profesionales':'Professional networks','Soporte TI':'IT support',
  'Experiencia con criterio':'Experience with purpose','Cada propiedad, empresa o centro educativo tiene retos distintos. Empezamos escuchando y terminamos con una instalación limpia, documentada y fácil de usar.':'Every home, business and school has different challenges. We begin by listening and finish with a clean, documented and easy-to-use installation.',
  'Cada espacio merece':'Every space deserves','una solución bien pensada.':'a well-designed solution.',
  'Proyectos y escenarios':'Projects and environments','Soluciones que pertenecen al lugar.':'Solutions that belong in the space.','La cámara correcta no es la más grande: es la que cubre el punto crítico, soporta el ambiente y entrega evidencia útil.':'The right camera is not the largest one: it covers the critical point, withstands the environment and delivers useful evidence.',
  'Vea la solución':'See the solution','en su propio espacio.':'in your own space.','Explore dónde se instalan los equipos, qué problema resuelven y cómo se conecta cada sistema.':'Explore where equipment is installed, what problem it solves and how each system connects.','Topología de ejemplo':'Example topology',
  'Soluciones en movimiento':'Solutions in motion','Vea la tecnología aplicada.':'See technology in action.','Recorridos visuales de soluciones reales, reproducidos en silencio para no interrumpir su navegación.':'Visual tours of real solutions, played silently so they never interrupt your browsing.','Protección conectada':'Connected protection','Espacios residenciales y comerciales':'Residential and commercial spaces','Visión inteligente':'Intelligent vision','Cobertura, análisis y respuesta':'Coverage, analytics and response',
  'Servicios en Costa Rica':'Services in Costa Rica','Instalación, monitoreo y mantenimiento.':'Installation, monitoring and maintenance.','Atención profesional para propietarios nacionales y extranjeros, en español e inglés, desde el Pacífico Central hacia el Pacífico Sur y zonas del Pacífico Norte.':'Professional service for Costa Rican and international property owners, in English and Spanish, from the Central Pacific to the South Pacific and parts of the North Pacific.',
  'Cámaras de seguridad':'Security cameras','Venta e instalación de cámaras CCTV e IP para viviendas, villas, condominios, hoteles, restaurantes, comercios y centros educativos.':'Sales and installation of CCTV and IP cameras for homes, villas, condominiums, hotels, restaurants, businesses and schools.','Hikvision y Dahua':'Hikvision and Dahua','Grabación y acceso remoto':'Recording and remote access','Alertas inteligentes':'Smart alerts',
  'Internet y redes Wi-Fi':'Internet and Wi-Fi networks','Instalación de Internet, cableado, redes profesionales, puntos de acceso y respaldo automático para mantener cámaras y operaciones conectadas.':'Internet, cabling, professional network, access point and automatic backup installation to keep cameras and operations connected.','MikroTik, Ruijie y UniFi':'MikroTik, Ruijie and UniFi','Wi-Fi profesional':'Professional Wi-Fi','Failover de Internet':'Internet failover',
  'Monitoreo y soporte':'Monitoring and support','Configuración de monitoreo remoto, revisión de instalaciones, diagnóstico de fallas y soporte técnico para sistemas de seguridad y conectividad.':'Remote monitoring setup, installation reviews, fault diagnosis and technical support for security and connectivity systems.','Revisión técnica':'Technical inspection','Soporte remoto':'Remote support','Optimización del sistema':'System optimization',
  'Mantenimiento preventivo':'Preventive maintenance','Limpieza, ajuste, pruebas y mantenimiento preventivo de cámaras, grabadores, redes y equipos para conservar imagen estable y evidencia útil.':'Cleaning, adjustment, testing and preventive maintenance for cameras, recorders, networks and equipment to preserve stable images and useful evidence.','Pruebas de grabación':'Recording tests','Estado de conexiones':'Connection health','Informe de recomendaciones':'Recommendations report',
  'Cobertura principal':'Primary coverage','Proyectos en Costa Rica':'Projects across Costa Rica',
  'Uvita · Residencial premium':'Uvita · Premium residential','Protección discreta, incluso frente al mar.':'Discreet protection, even by the ocean.','Diseño perimetral para accesos, parqueo y áreas sociales, con equipos preparados para humedad y salinidad. Monitoreo remoto sin invadir la arquitectura.':'Perimeter design for entrances, parking and social areas, with equipment suited for humidity and sea air. Remote monitoring without disrupting the architecture.',
  'Visión nocturna a color':'Full-color night vision','Alertas por personas y vehículos':'Person and vehicle alerts','Grabación local y acceso remoto':'Local recording and remote access',
  'Manuel Antonio · Villa turística':'Manuel Antonio · Vacation villa','Control de la propiedad desde cualquier lugar.':'Control your property from anywhere.','Cobertura pensada para residencias vacacionales: entradas, terrazas y perímetro, con zonas de privacidad y una red capaz de mantener video estable.':'Coverage designed for vacation properties: entrances, terraces and perimeter, with privacy zones and a network built for stable video.',
  'Visualización desde el teléfono':'View from your phone','Audio y verificación en tiempo real':'Real-time audio and verification','Instalación limpia y documentada':'Clean, documented installation',
  'Más que viviendas':'Beyond homes','Una infraestructura, muchos usos.':'One infrastructure, many uses.','Educación · Hotelería · Comercio':'Education · Hospitality · Retail','Conectar, proteger y mantener operando.':'Connect, protect and keep operating.',
  'En un colegio, la misma red puede conectar laboratorios, administración, cámaras y telefonía sin mezclar información sensible. En un hotel o comercio, la segmentación mantiene separados huéspedes, operación y seguridad.':'In a school, one network can connect labs, administration, cameras and telephony without mixing sensitive information. In a hotel or business, segmentation keeps guests, operations and security separate.',
  'Separa usuarios y servicios':'Separates users and services','Datos y energía por un cable':'Data and power over one cable','Internet de respaldo automático':'Automatic Internet backup','Monitoreo y soporte remoto':'Remote monitoring and support',
  'Cómo trabajamos':'How we work','Visita y diagnóstico':'Site visit and assessment','Entendemos el espacio, los riesgos y la cobertura.':'We understand the space, risks and coverage.','Diseño y propuesta':'Design and proposal','Definimos equipos, ubicaciones y alcance.':'We define equipment, locations and scope.','Instalación profesional':'Professional installation','Configuramos, probamos y documentamos.':'We configure, test and document.','Acompañamiento':'Ongoing support','Capacitamos y damos soporte cuando lo necesite.':'We train your team and support you when needed.',
  'Tecnología con propósito':'Technology with purpose','Elegimos la plataforma según el proyecto.':'We choose the platform for the project.',
  'Analítica AcuSense, ColorVu y soluciones IP para proyectos que requieren clasificación precisa de eventos, detalle nocturno e integración escalable.':'AcuSense analytics, ColorVu and IP solutions for projects requiring accurate event classification, night detail and scalable integration.',
  'Opciones versátiles para hogar, comercio y hotelería: WizSense, cámaras activas y equipos de doble lente con seguimiento y disuasión.':'Versatile options for homes, retail and hospitality: WizSense, active deterrence and dual-lens cameras with tracking.',
  'Administra enlaces de Internet, VPN, ancho de banda y failover. Puede trabajar junto a switches y puntos de acceso Ruijie/Reyee para mantener una red estable, segmentada y administrable.':'Manages Internet links, VPN, bandwidth and failover. It can work with Ruijie/Reyee switches and access points to maintain a stable, segmented and manageable network.',
  'Wi-Fi administrado, switches PoE y cobertura de alta densidad para hoteles, colegios, oficinas y propiedades de gran extensión.':'Managed Wi-Fi, PoE switches and high-density coverage for hotels, schools, offices and large properties.',
  'Una plataforma integrada de Ubiquiti para gateways, switching, Wi-Fi y administración centralizada. Permite visualizar toda la red desde una sola interfaz y configurar respaldo de Internet según el gateway utilizado.':'Ubiquiti’s integrated platform for gateways, switching, Wi-Fi and centralized management. It provides a single view of the network and Internet backup options according to the gateway used.',
  'Internet que no se detiene':'Internet that keeps working','Failover con MikroTik, Ruijie y UniFi.':'Failover with MikroTik, Ruijie and UniFi.','Un gateway compatible de MikroTik, Ruijie/Reyee o UniFi supervisa dos conexiones, por ejemplo fibra y Starlink. Si la principal deja de responder, activa automáticamente el enlace de respaldo. La red mantiene conectados el Wi-Fi, las cámaras y la operación sin que el usuario tenga que cambiar nada.':'A compatible MikroTik, Ruijie/Reyee or UniFi gateway monitors two connections, such as fiber and Starlink. If the primary link stops responding, it automatically activates the backup. Wi-Fi, cameras and operations stay connected without any action from the user.',
  'Consultar una solución':'Ask about a solution','Fibra':'Fiber','Enlace principal':'Primary link','Enlace de respaldo':'Backup link','Supervisa · detecta · cambia automáticamente':'Monitors · detects · switches automatically','Cámaras':'Cameras','Operación':'Operations',
  'Quepos · Pacífico Central · Todo Costa Rica':'Quepos · Central Pacific · All Costa Rica','Cuéntenos qué necesita proteger o conectar.':'Tell us what you need to protect or connect.','Una conversación breve es suficiente para comenzar a darle forma al proyecto.':'A short conversation is enough to start shaping your project.','Escribir al 8333-5665':'Message 8333-5665',
  'Dirección técnica':'Technical leadership','Ingeniero de Sistemas, docente de Robótica e Informática y especialista en infraestructura y soporte TI.':'Systems Engineer, Robotics and Computing instructor, and infrastructure and IT support specialist.','años en tecnología':'years in technology','Redes Cisco':'Cisco networking','Inglés avanzado':'Advanced English',
  'Ingeniería de Sistemas':'Systems Engineering','Redes LAN / WAN':'LAN / WAN networks','Ciberseguridad':'Cybersecurity','Control de calidad':'Quality assurance','Docencia tecnológica':'Technology education','Tienda y catálogo':'Store and catalog','Tienda y catálogo ↗':'Store and catalog ↗','Ver tienda ↗':'View store ↗','WhatsApp directo · +506 8333-5665':'Direct WhatsApp · +506 8333-5665','WhatsApp directo · +506 8333-5665 ↗':'Direct WhatsApp · +506 8333-5665 ↗','Facebook oficial ↗':'Official Facebook ↗','Instagram oficial ↗':'Official Instagram ↗'
};

const textNodes=[];
const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement.closest('script,style')||!n.nodeValue.trim()?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT});
while(walker.nextNode()){const node=walker.currentNode;node._es=node.nodeValue;textNodes.push(node)}

function setLanguage(lang){
  document.documentElement.lang=lang;
  textNodes.forEach(node=>{const original=node._es;const trimmed=original.trim();const replacement=lang==='en'&&translations[trimmed]?translations[trimmed]:trimmed;node.nodeValue=original.replace(trimmed,replacement)});
  document.querySelectorAll('[data-lang]').forEach(button=>{const active=button.dataset.lang===lang;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});
  menu.textContent=nav.classList.contains('open')?(lang==='en'?'Close':'Cerrar'):(lang==='en'?'Menu':'Menú');
  localStorage.setItem('intertech-language',lang);
  renderSector(activeSector,lang);
}

menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?(document.documentElement.lang==='en'?'Close':'Cerrar'):(document.documentElement.lang==='en'?'Menu':'Menú')});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent=document.documentElement.lang==='en'?'Menu':'Menú'}));
document.querySelectorAll('[data-lang]').forEach(button=>button.addEventListener('click',()=>setLanguage(button.dataset.lang)));

const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
window.addEventListener('scroll',()=>topbar.classList.toggle('scrolled',scrollY>80),{passive:true});
hero.addEventListener('pointermove',event=>{const rect=hero.getBoundingClientRect();hero.style.setProperty('--mx',((event.clientX-rect.left)/rect.width-.5).toFixed(3));hero.style.setProperty('--my',((event.clientY-rect.top)/rect.height-.5).toFixed(3))});
hero.addEventListener('pointerleave',()=>{hero.style.setProperty('--mx',0);hero.style.setProperty('--my',0)});
document.getElementById('year').textContent=new Date().getFullYear();

const sectorData={
  villa:{image:'assets/hero-uvita.png',place:['Villa · Uvita','Villa · Uvita'],title:['Protección discreta para disfrutar con tranquilidad.','Discreet protection, designed for peace of mind.'],description:['Cobertura en accesos, parqueo y áreas sociales, diseñada para el clima tropical y controlada desde el teléfono.','Coverage for entrances, parking and social areas, designed for tropical weather and controlled from your phone.'],zones:[['Entrada','Parqueo','Terraza','Perímetro'],['Entrance','Parking','Terrace','Perimeter']],benefit:['Monitoreo remoto, alertas útiles y evidencia clara sin invadir la arquitectura.','Remote monitoring, useful alerts and clear evidence without disrupting the architecture.'],hotspots:[[18,67],[48,63],[76,48]],topology:['Una sola red, toda la propiedad.','One network across the entire property.']},
  apartment:{image:'assets/sector-apartment.png',place:['Condominio · Apartamentos','Condominium · Apartments'],title:['Accesos ordenados y áreas comunes más seguras.','Controlled access and safer shared spaces.'],description:['Integra ingreso peatonal y vehicular, parqueos, ascensores y zonas comunes con administración centralizada.','Integrates pedestrian and vehicle access, parking, elevators and common areas with centralized management.'],zones:[['Portón','Lobby','Parqueo','Área común'],['Gate','Lobby','Parking','Common area']],benefit:['Permite investigar eventos rápidamente y administrar múltiples edificios desde un mismo punto.','Investigate events quickly and manage multiple buildings from one place.'],hotspots:[[24,61],[50,43],[78,67]],topology:['Cobertura compartida, administración central.','Shared coverage, centralized management.']},
  restaurant:{image:'assets/sector-restaurant.png',place:['Restaurante · Operación completa','Restaurant · Complete operation'],title:['Visibilidad para proteger clientes, equipo y operación.','Visibility that protects guests, staff and operations.'],description:['La solución cubre entrada, salón, caja, cocina y oficina respetando la experiencia del cliente.','The solution covers entrance, dining room, cashier, kitchen and office while respecting the guest experience.'],zones:[['Entrada','Salón','Caja','Cocina'],['Entrance','Dining room','Cashier','Kitchen']],benefit:['Ayuda a aclarar incidentes, supervisar procesos y reducir puntos ciegos en horas de mayor actividad.','Helps clarify incidents, supervise processes and reduce blind spots during peak hours.'],hotspots:[[19,50],[49,43],[77,58]],topology:['Video y operación conectados sin estorbar al servicio.','Video and operations connected without disrupting service.']},
  garden:{image:'assets/sector-garden.png',place:['Jardín · Perímetro exterior','Garden · Outdoor perimeter'],title:['Detección temprana antes de llegar a la vivienda.','Early detection before anyone reaches the home.'],description:['Cámaras exteriores, iluminación y alertas protegen senderos, portones, jardines y límites de propiedad.','Outdoor cameras, lighting and alerts protect paths, gates, gardens and property boundaries.'],zones:[['Sendero','Portón','Piscina','Cerca'],['Path','Gate','Pool','Fence']],benefit:['Equipos resistentes al clima permiten vigilar áreas amplias con menos falsas alarmas.','Weather-resistant equipment monitors large areas with fewer false alarms.'],hotspots:[[12,18],[73,48],[93,24]],topology:['Perímetro inteligente conectado al sistema principal.','Smart perimeter connected to the main system.']},
  hotel:{image:'assets/sector-hotel.png',place:['Hotel · Experiencia y seguridad','Hotel · Guest experience and security'],title:['Seguridad que acompaña al huésped sin hacerse notar.','Security that supports guests without getting in the way.'],description:['Recepción, lobby, pasillos, piscina y zonas de servicio operan sobre una infraestructura estable y segmentada.','Reception, lobby, corridors, pool and service areas run on stable, segmented infrastructure.'],zones:[['Recepción','Lobby','Pasillos','Piscina'],['Reception','Lobby','Corridors','Pool']],benefit:['Una vista central facilita responder a incidentes y mantener separadas las redes de huéspedes, operación y cámaras.','A central view simplifies incident response while keeping guest, operations and camera networks separate.'],hotspots:[[19,55],[51,42],[80,64]],topology:['Seguridad, Wi-Fi y operación sobre redes separadas.','Security, Wi-Fi and operations on separate networks.']},
  gas:{image:'assets/sector-gas-station.png',place:['Gasolinera · Operación crítica','Gas station · Critical operation'],title:['Evidencia clara en cada punto de la operación.','Clear evidence at every operational point.'],description:['Cobertura especializada para islas, descarga de combustible, tienda, caja, accesos y oficina.','Specialized coverage for pumps, fuel unloading, store, cashier, entrances and office.'],zones:[['Islas','Descarga','Tienda','Caja'],['Pumps','Unloading','Store','Cashier']],benefit:['Las cámaras correctas ayudan a documentar transacciones, maniobras y eventos en áreas de alto riesgo.','The right cameras document transactions, maneuvers and events in high-risk areas.'],hotspots:[[22,56],[55,46],[82,62]],topology:['Áreas críticas conectadas a grabación y supervisión.','Critical areas connected to recording and supervision.']}
};
let activeSector='villa';
const sectorOrder=Object.keys(sectorData);
function renderSector(key,lang=document.documentElement.lang){
  if(!sectorData[key])return; activeSector=key; const d=sectorData[key],i=lang==='en'?1:0;
  const tabLabels={villa:['Villa','Villa'],apartment:['Apartamento','Apartment'],restaurant:['Restaurante','Restaurant'],garden:['Jardín','Garden'],hotel:['Hotel','Hotel'],gas:['Gasolinera','Gas station']};
  document.querySelectorAll('[data-sector]').forEach(b=>{b.classList.toggle('active',b.dataset.sector===key);b.setAttribute('aria-selected',String(b.dataset.sector===key));b.textContent=tabLabels[b.dataset.sector][i]});
  const image=document.getElementById('sector-image'); image.src=d.image; image.alt=d.title[i];
  document.getElementById('sector-place').textContent=d.place[i];document.getElementById('sector-title').textContent=d.title[i];document.getElementById('sector-description').textContent=d.description[i];document.getElementById('sector-benefit').textContent=d.benefit[i];document.getElementById('topology-title').textContent=d.topology[i];
  document.getElementById('sector-zone-label').textContent=i?'Application areas':'Áreas de aplicación';document.getElementById('sector-view-label').textContent=i?'Solution view':'Vista de solución';
  document.getElementById('topology-copy').textContent=i?'The recorder preserves evidence; the PoE switch connects and powers the cameras; the app enables remote supervision.':'El grabador conserva la evidencia; el switch PoE conecta y alimenta las cámaras; la aplicación permite supervisar a distancia.';
  document.getElementById('sector-zones').innerHTML=d.zones[i].map(z=>`<span>${z}</span>`).join('');document.getElementById('topology-endpoints').innerHTML=d.zones[i].map(z=>`<span>${z}</span>`).join('');
  document.getElementById('sector-hotspots').innerHTML=d.hotspots.map((p,n)=>`<div class="hotspot" style="--x:${p[0]}%;--y:${p[1]}%"><b></b><span>${d.zones[i][n]}</span></div>`).join('');
  document.querySelector('.sector-progress i').style.animation='none';requestAnimationFrame(()=>document.querySelector('.sector-progress i').style.animation='');
}
document.querySelectorAll('[data-sector]').forEach(button=>button.addEventListener('click',()=>renderSector(button.dataset.sector)));
if(!matchMedia('(prefers-reduced-motion: reduce)').matches)setInterval(()=>renderSector(sectorOrder[(sectorOrder.indexOf(activeSector)+1)%sectorOrder.length]),9000);

const motionVideos=[...document.querySelectorAll('.motion-card video')];
const loadAndPlay=video=>{if(!video.src){video.src=video.dataset.src;video.load()}video.play().then(()=>video.closest('.motion-card').classList.add('playing')).catch(()=>{})};
const videoObserver=new IntersectionObserver(entries=>entries.forEach(({target,isIntersecting})=>{if(isIntersecting)loadAndPlay(target);else{target.pause();target.closest('.motion-card').classList.remove('playing')}}),{rootMargin:'180px 0px',threshold:.15});
motionVideos.forEach(video=>{videoObserver.observe(video);video.closest('.motion-card').addEventListener('click',()=>{if(video.paused)loadAndPlay(video);else{video.pause();video.closest('.motion-card').classList.remove('playing')}})});
setLanguage(localStorage.getItem('intertech-language')==='en'?'en':'es');
